runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://connect.master:4zdkoWb9CPmTvbHi9MtC3Qhz@ds061506.mlab.com:61506/connect-development
  APP_ID: SjJk1ZiGY6w84YoZ48UjTGGl
  MASTER_KEY: HRd7oa3G3AHH326Fsz3gzBUR
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  